[package]
name = "tikv-importer"
version = "4.0.0-alpha"
authors = ["The TiKV Authors"]
description = "Tool to help ingesting large number of KV pairs into TiKV cluster"
license = "Apache-2.0"
repository = "https://github.com/tikv/importer/"
edition = "2018"
publish = false

[lib]
name = "tikv_importer"

[[bin]]
name = "tikv-importer"

[[test]]
name = "integrations"
path = "tests/integrations/import/mod.rs"

[dependencies]
clap = "2.33"
cmd = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
crc = "1.8"
crossbeam = "0.7"
engine = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
futures = "0.1"
futures-cpupool = "0.1"
grpcio = "0.5.0-alpha.5"
kvproto = { version = "0.0.2", git = "https://github.com/pingcap/kvproto.git", branch = "master" }
lazy_static = "1.4"
log_wrappers = { version = "0.0.1", git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
pd_client = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
prometheus = { version = "0.8", default-features = false, features = ["nightly", "push", "process"], git = "https://github.com/pingcap/rust-prometheus.git", rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be" }
quick-error = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
tikv_util = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }
tipb = { git = "https://github.com/pingcap/tipb.git" }
toml = "0.4"
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[dependencies.engine_rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
tempdir = "0.3"
rand = "0.7"
test_util = { git = "https://github.com/tikv/tikv.git", rev = "2e0379c" }

[features]
default = ['tikv/default']
tcmalloc = ['tikv/tcmalloc']
jemalloc = ['tikv/jemalloc']
portable = ['tikv/portable']
sse = ['tikv/sse']
mem-profiling = ['tikv/mem-profiling']

[replace]
"raft:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }
"raft-proto:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }
"protobuf-codegen:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"protobuf:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
